CREATE SCHEMA "auth";
--> statement-breakpoint
CREATE SCHEMA "education";
--> statement-breakpoint
CREATE SCHEMA "health";
--> statement-breakpoint
CREATE TABLE "auth"."account" (
	"id" varchar(32) PRIMARY KEY NOT NULL,
	"account_id" varchar(100) NOT NULL,
	"provider_id" varchar(50) NOT NULL,
	"user_id" varchar(32) NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp with time zone,
	"refresh_token_expires_at" timestamp with time zone,
	"scope" varchar(500),
	"password" varchar(255),
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auth"."invitation" (
	"id" varchar(32) PRIMARY KEY NOT NULL,
	"organization_id" varchar(32) NOT NULL,
	"email" varchar(254) NOT NULL,
	"role" text,
	"team_id" text,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"inviter_id" varchar(32) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auth"."member" (
	"id" varchar(32) PRIMARY KEY NOT NULL,
	"organization_id" varchar(32) NOT NULL,
	"user_id" varchar(32) NOT NULL,
	"role" varchar(50) DEFAULT 'member' NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auth"."organization" (
	"id" varchar(32) PRIMARY KEY NOT NULL,
	"name" varchar(100) NOT NULL,
	"active" boolean NOT NULL,
	"slug" varchar(100),
	"logo" varchar(500),
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"metadata" text,
	"type" varchar(20) NOT NULL,
	CONSTRAINT "organization_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "auth"."organization_role" (
	"id" varchar(32) PRIMARY KEY NOT NULL,
	"organization_id" varchar(32) NOT NULL,
	"role" varchar(50) NOT NULL,
	"permission" varchar(100) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "auth"."passkey" (
	"id" varchar(32) PRIMARY KEY NOT NULL,
	"name" varchar(100),
	"public_key" text NOT NULL,
	"user_id" varchar(32) NOT NULL,
	"credential_id" varchar(255) NOT NULL,
	"counter" integer NOT NULL,
	"device_type" varchar(50) NOT NULL,
	"backed_up" boolean NOT NULL,
	"transports" varchar(255),
	"created_at" timestamp with time zone,
	"aaguid" varchar(36)
);
--> statement-breakpoint
CREATE TABLE "auth"."region" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth"."region_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"type" varchar NOT NULL,
	"code" varchar(7) NOT NULL,
	"parent_id" integer
);
--> statement-breakpoint
CREATE TABLE "auth"."session" (
	"id" varchar(32) PRIMARY KEY NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"token" varchar(255) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"ip_address" varchar(45),
	"user_agent" varchar(500),
	"user_id" varchar(32) NOT NULL,
	"active_organization_id" varchar(32),
	"active_team_id" varchar(32),
	"impersonated_by" varchar(32),
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "auth"."team" (
	"id" varchar(32) PRIMARY KEY NOT NULL,
	"name" varchar(100) NOT NULL,
	"role" varchar(50) NOT NULL,
	"organization_id" varchar(32) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "auth"."team_member" (
	"id" varchar(32) PRIMARY KEY NOT NULL,
	"team_id" varchar(32) NOT NULL,
	"user_id" varchar(32) NOT NULL,
	"created_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "auth"."user" (
	"id" varchar(32) PRIMARY KEY NOT NULL,
	"name" varchar(100) NOT NULL,
	"surname" varchar(100) NOT NULL,
	"email" varchar(254) NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" varchar(500),
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"role" varchar(50),
	"banned" boolean DEFAULT false,
	"ban_reason" text,
	"is_anonymous" boolean,
	"ban_expires" timestamp with time zone,
	"document_type" varchar(20) NOT NULL,
	"document_number" varchar(20) NOT NULL,
	"sex" char NOT NULL,
	"birth_date" date NOT NULL,
	"phone" varchar(15) NOT NULL,
	"region_id" integer NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "auth"."verification" (
	"id" varchar(32) PRIMARY KEY NOT NULL,
	"identifier" varchar(100) NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "education"."fair" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "education"."fair_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(200) NOT NULL,
	"address" text NOT NULL,
	"region_id" integer NOT NULL,
	"created_by" varchar(32),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"start_time" time with time zone NOT NULL,
	"end_time" time with time zone NOT NULL,
	"date" date NOT NULL,
	"assistance_count" integer,
	"fourth_grade_assistance" integer,
	"fifth_grade_assistance" integer
);
--> statement-breakpoint
CREATE TABLE "education"."fair_organization" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "education"."fair_organization_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fair_id" integer NOT NULL,
	"organization_id" varchar(32) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "education"."organization_location" (
	"organization_id" varchar(32) NOT NULL,
	"region_id" integer NOT NULL,
	"address" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(32) NOT NULL,
	"state" boolean DEFAULT true NOT NULL,
	CONSTRAINT "organization_location_organization_id_region_id_pk" PRIMARY KEY("organization_id","region_id")
);
--> statement-breakpoint
CREATE TABLE "education"."organization_major" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "education"."organization_major_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"organization_id" varchar(32) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "education"."opportunity" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "education"."opportunity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(200) NOT NULL,
	"organization_id" varchar(32) NOT NULL,
	"description" text NOT NULL,
	"type" varchar(20) NOT NULL,
	"created_by" varchar(32) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "education"."report_reason" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "education"."report_reason_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(32) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "education"."scholarship" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "education"."scholarship_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"organization_id" varchar(32) NOT NULL,
	"created_by" varchar(32) NOT NULL,
	"description" text NOT NULL,
	"requirements" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"type" varchar(2) NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"vacancies" integer NOT NULL,
	"active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "education"."scholarship_application" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "education"."scholarship_application_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"scholarship_id" integer NOT NULL,
	"user_id" varchar(32) NOT NULL,
	"application_date" timestamp with time zone DEFAULT now() NOT NULL,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"reviewed_by" varchar(32),
	"review_date" timestamp with time zone,
	"comments" text
);
--> statement-breakpoint
CREATE TABLE "education"."scholarship_major" (
	"scholarship_id" integer NOT NULL,
	"major_id" integer NOT NULL,
	CONSTRAINT "scholarship_major_scholarship_id_major_id_pk" PRIMARY KEY("scholarship_id","major_id")
);
--> statement-breakpoint
CREATE TABLE "education"."scholarship_student_report" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "education"."scholarship_student_report_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"scholarship_id" integer NOT NULL,
	"user_id" varchar(32) NOT NULL,
	"reported_by" varchar(32) NOT NULL,
	"cause" varchar(20) NOT NULL,
	"cause_detail" text,
	"reason" integer,
	"reason_detail" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "education"."student_info" (
	"user_id" varchar(32) PRIMARY KEY NOT NULL,
	"guardian_email" varchar(254) NOT NULL,
	"grade" varchar(50) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "health"."activity" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "health"."activity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"date" date NOT NULL,
	"duration" interval hour NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"space_id" varchar(32) NOT NULL,
	"region_id" integer NOT NULL,
	"address" varchar(200) NOT NULL,
	"status_id" integer NOT NULL,
	"type_id" integer NOT NULL,
	"user_id" varchar(32) NOT NULL,
	"state" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "health"."activity_status" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "health"."activity_status_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "health"."activity_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "health"."activity_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "health"."activity_user" (
	"user_id" varchar(32) NOT NULL,
	"activity_id" integer NOT NULL,
	"rewarded" boolean DEFAULT false NOT NULL,
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "activity_user_user_id_activity_id_pk" PRIMARY KEY("user_id","activity_id")
);
--> statement-breakpoint
CREATE TABLE "health"."allied_participation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "health"."allied_participation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"activity_id" integer NOT NULL,
	"allied_id" varchar(32) NOT NULL,
	"speciality_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "health"."attention" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "health"."attention_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"observations" text,
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL,
	"user_id" varchar(32) NOT NULL,
	"allied_participation_id" integer NOT NULL,
	"registered_by" varchar(32) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "health"."patient_info" (
	"user_id" varchar(32) PRIMARY KEY NOT NULL,
	"insurance_type" varchar(20) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "health"."speciality" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "health"."speciality_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "unique_speciality_name" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "auth"."account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."invitation" ADD CONSTRAINT "invitation_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."invitation" ADD CONSTRAINT "invitation_inviter_id_user_id_fk" FOREIGN KEY ("inviter_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."member" ADD CONSTRAINT "member_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."member" ADD CONSTRAINT "member_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."organization_role" ADD CONSTRAINT "organization_role_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."passkey" ADD CONSTRAINT "passkey_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."region" ADD CONSTRAINT "region_parent_id_region_id_fk" FOREIGN KEY ("parent_id") REFERENCES "auth"."region"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."team" ADD CONSTRAINT "team_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."team_member" ADD CONSTRAINT "team_member_team_id_team_id_fk" FOREIGN KEY ("team_id") REFERENCES "auth"."team"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."team_member" ADD CONSTRAINT "team_member_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth"."user" ADD CONSTRAINT "user_region_id_region_id_fk" FOREIGN KEY ("region_id") REFERENCES "auth"."region"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."fair" ADD CONSTRAINT "fair_region_id_region_id_fk" FOREIGN KEY ("region_id") REFERENCES "auth"."region"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."fair" ADD CONSTRAINT "fair_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."fair_organization" ADD CONSTRAINT "fair_organization_fair_id_fair_id_fk" FOREIGN KEY ("fair_id") REFERENCES "education"."fair"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."fair_organization" ADD CONSTRAINT "fair_organization_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."organization_location" ADD CONSTRAINT "organization_location_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."organization_location" ADD CONSTRAINT "organization_location_region_id_region_id_fk" FOREIGN KEY ("region_id") REFERENCES "auth"."region"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."organization_location" ADD CONSTRAINT "organization_location_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."organization_major" ADD CONSTRAINT "organization_major_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."opportunity" ADD CONSTRAINT "opportunity_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."opportunity" ADD CONSTRAINT "opportunity_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."report_reason" ADD CONSTRAINT "report_reason_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."scholarship" ADD CONSTRAINT "scholarship_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."scholarship" ADD CONSTRAINT "scholarship_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."scholarship_application" ADD CONSTRAINT "scholarship_application_scholarship_id_scholarship_id_fk" FOREIGN KEY ("scholarship_id") REFERENCES "education"."scholarship"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."scholarship_application" ADD CONSTRAINT "scholarship_application_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."scholarship_application" ADD CONSTRAINT "scholarship_application_reviewed_by_user_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."scholarship_major" ADD CONSTRAINT "scholarship_major_scholarship_id_scholarship_id_fk" FOREIGN KEY ("scholarship_id") REFERENCES "education"."scholarship"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."scholarship_major" ADD CONSTRAINT "scholarship_major_major_id_organization_major_id_fk" FOREIGN KEY ("major_id") REFERENCES "education"."organization_major"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."scholarship_student_report" ADD CONSTRAINT "scholarship_student_report_scholarship_id_scholarship_id_fk" FOREIGN KEY ("scholarship_id") REFERENCES "education"."scholarship"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."scholarship_student_report" ADD CONSTRAINT "scholarship_student_report_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."scholarship_student_report" ADD CONSTRAINT "scholarship_student_report_reported_by_user_id_fk" FOREIGN KEY ("reported_by") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."scholarship_student_report" ADD CONSTRAINT "scholarship_student_report_reason_report_reason_id_fk" FOREIGN KEY ("reason") REFERENCES "education"."report_reason"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "education"."student_info" ADD CONSTRAINT "student_info_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health"."activity" ADD CONSTRAINT "activity_space_id_organization_id_fk" FOREIGN KEY ("space_id") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health"."activity" ADD CONSTRAINT "activity_region_id_region_id_fk" FOREIGN KEY ("region_id") REFERENCES "auth"."region"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health"."activity" ADD CONSTRAINT "activity_status_id_activity_status_id_fk" FOREIGN KEY ("status_id") REFERENCES "health"."activity_status"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health"."activity" ADD CONSTRAINT "activity_type_id_activity_type_id_fk" FOREIGN KEY ("type_id") REFERENCES "health"."activity_type"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health"."activity" ADD CONSTRAINT "activity_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE set default ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health"."activity_user" ADD CONSTRAINT "activity_user_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health"."activity_user" ADD CONSTRAINT "activity_user_activity_id_activity_id_fk" FOREIGN KEY ("activity_id") REFERENCES "health"."activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health"."allied_participation" ADD CONSTRAINT "allied_participation_activity_id_activity_id_fk" FOREIGN KEY ("activity_id") REFERENCES "health"."activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health"."allied_participation" ADD CONSTRAINT "allied_participation_allied_id_organization_id_fk" FOREIGN KEY ("allied_id") REFERENCES "auth"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health"."allied_participation" ADD CONSTRAINT "allied_participation_speciality_id_speciality_id_fk" FOREIGN KEY ("speciality_id") REFERENCES "health"."speciality"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health"."attention" ADD CONSTRAINT "attention_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health"."attention" ADD CONSTRAINT "attention_allied_participation_id_allied_participation_id_fk" FOREIGN KEY ("allied_participation_id") REFERENCES "health"."allied_participation"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health"."attention" ADD CONSTRAINT "attention_registered_by_user_id_fk" FOREIGN KEY ("registered_by") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health"."patient_info" ADD CONSTRAINT "patient_info_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "location_code_idx" ON "auth"."region" USING btree ("code");--> statement-breakpoint
CREATE UNIQUE INDEX "user_document_number_idx" ON "auth"."user" USING btree ("document_number");--> statement-breakpoint
CREATE UNIQUE INDEX "user_phone_idx" ON "auth"."user" USING btree ("phone");--> statement-breakpoint
CREATE VIEW "health"."attention_fact" AS (select "health"."attention"."id" as "attentionId", "health"."attention"."timestamp" as "timestamp", "health"."speciality"."name" as "speciality", "auth"."organization"."name" as "alliedOrganization", "health"."attention"."user_id" as "patientId", "auth"."user"."sex" as "patientSex", FLOOR(DATE_PART('year', AGE(NOW(), "auth"."user"."birth_date"))) as "patientAge", "auth"."user"."document_type" as "patientDocumentType", "health"."patient_info"."insurance_type" as "patientInsuranceType", "health"."activity"."id" as "activityId", "health"."activity"."name" as "activityName", "health"."activity"."date" as "activityDate", "registrations", "rewarded", "newParticipants", "auth"."region"."name" as "activityRegion", "health"."activity_type"."name" as "activityType", "health"."activity_status"."name" as "activityStatus" from "health"."attention" inner join "health"."allied_participation" on "health"."attention"."allied_participation_id" = "health"."allied_participation"."id" inner join "health"."activity" on "health"."allied_participation"."activity_id" = "health"."activity"."id" inner join "auth"."organization" on "health"."allied_participation"."allied_id" = "auth"."organization"."id" inner join "health"."speciality" on "health"."allied_participation"."speciality_id" = "health"."speciality"."id" inner join "auth"."region" on "health"."activity"."region_id" = "auth"."region"."id" inner join "health"."activity_type" on "health"."activity"."type_id" = "health"."activity_type"."id" inner join "health"."activity_status" on "health"."activity"."status_id" = "health"."activity_status"."id" inner join "health"."patient_info" on "health"."attention"."user_id" = "health"."patient_info"."user_id" inner join "auth"."user" on "health"."attention"."user_id" = "auth"."user"."id" left join (select activity_user.activity_id as "activityId", count("health"."activity_user"."user_id") as "registrations", COUNT(CASE WHEN "health"."activity_user"."rewarded" = true THEN 1 END) as "rewarded", 
      COUNT(DISTINCT activity_user.user_id)
      FILTER (
        WHERE NOT EXISTS (
          SELECT 1
          FROM "health"."activity_user" au2
          WHERE au2.user_id = activity_user.user_id
          AND au2.timestamp < activity_user.timestamp
        )
      )
       as "newParticipants" from "health"."activity_user" inner join "health"."activity" on "health"."activity_user"."activity_id" = "health"."activity"."id" inner join "health"."activity_status" on "health"."activity"."status_id" = "health"."activity_status"."id" where "health"."activity_status"."name" <> 'Cancelado' group by "health"."activity_user"."activity_id") "activity_user_stats" on "health"."activity"."id" = "activityId" where "health"."activity_status"."name" <> 'Cancelado');