- name: Configuración de servidor con Docker
  hosts: vps
  become: true
  vars:
    base_src_path: "{{ base_src_path | default('../base') }}"

  roles:
    - role: geerlingguy.docker
      vars:
        docker_install_compose_plugin: true

  tasks:
    - name: Crear carpeta destino para el proyecto
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/app/base
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copiar archivos del compose base
      ansible.builtin.copy:
        src: "{{ base_src_path }}/"
        dest: /home/{{ ansible_user }}/app/base/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Crear red docker 'nginx-proxy' si no existe
      community.docker.docker_network:
        name: nginx-proxy
        state: present

    - name: Levantar stack con docker compose
      community.docker.docker_compose_v2:
        project_src: /home/{{ ansible_user }}/app/base/
        state: present
