services:
  caritas-dev-api:
    image: ${CARITAS_API_IMAGE:-ghcr.io/fabzio/caritas-api:latest}
    container_name: ${CARITAS_API_CONTAINER:-caritas-dev-api}
    environment:
      - VIRTUAL_HOST=${CARITAS_DOMAIN:-caritas.dev.fabzio.ip-ddns.com}
      - LETSENCRYPT_HOST=${CARITAS_DOMAIN:-caritas.dev.fabzio.ip-ddns.com}
      - LETSENCRYPT_EMAIL=${CARITAS_LE_EMAIL:-fmontoya@pucp.edu.pe}
      - VIRTUAL_PORT=${CARITAS_API_PORT:-8000}
      - VIRTUAL_PATH=${CARITAS_API_PATH:-/api}
  caritas-dev-frontend:
    image: ${CARITAS_FRONTEND_IMAGE:-ghcr.io/fabzio/caritas-frontend:latest}
    container_name: ${CARITAS_FRONTEND_CONTAINER:-caritas-dev-frontend}
    environment:
      - VIRTUAL_HOST=${CARITAS_DOMAIN:-caritas.dev.fabzio.ip-ddns.com}
      - LETSENCRYPT_HOST=${CARITAS_DOMAIN:-caritas.dev.fabzio.ip-ddns.com}
      - LETSENCRYPT_EMAIL=${CARITAS_LE_EMAIL:-fmontoya@pucp.edu.pe}
      - VIRTUAL_PORT=${CARITAS_FRONTEND_PORT:-80}
      - VIRTUAL_PATH=${CARITAS_FRONTEND_PATH:-/}

networks:
  default:
    name: ${CARITAS_NETWORK:-nginx-proxy}
    external: true
