/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LandingIndexRouteImport } from './routes/landing/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as LandingApplyRouteImport } from './routes/landing/apply'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthenticatedUserRouteImport } from './routes/_authenticated/user'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOrganizationRouteImport } from './routes/_authenticated/organization'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedEducationRouteImport } from './routes/_authenticated/education'
import { Route as AuthenticatedBeneficiaryRouteImport } from './routes/_authenticated/beneficiary'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthWelcomeIndexRouteImport } from './routes/auth/welcome_/index'
import { Route as AuthenticatedUserIndexRouteImport } from './routes/_authenticated/user/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedOrganizationIndexRouteImport } from './routes/_authenticated/organization/index'
import { Route as AuthenticatedHealthIndexRouteImport } from './routes/_authenticated/health/index'
import { Route as AuthenticatedEducationIndexRouteImport } from './routes/_authenticated/education/index'
import { Route as AuthenticatedBeneficiaryIndexRouteImport } from './routes/_authenticated/beneficiary/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedUserOrganizationsRouteImport } from './routes/_authenticated/user/organizations'
import { Route as AuthenticatedUserEducationRouteImport } from './routes/_authenticated/user/education'
import { Route as AuthenticatedSettingsInvitationsRouteImport } from './routes/_authenticated/settings/invitations'
import { Route as AuthenticatedSettingsAuthenticationRouteImport } from './routes/_authenticated/settings/authentication'
import { Route as AuthenticatedAdminOrganizationsRouteImport } from './routes/_authenticated/admin/organizations'
import { Route as AuthenticatedHealthSpecialityIndexRouteImport } from './routes/_authenticated/health/speciality/index'
import { Route as AuthenticatedHealthAlliesIndexRouteImport } from './routes/_authenticated/health/allies/index'
import { Route as AuthenticatedHealthActivitiesIndexRouteImport } from './routes/_authenticated/health/activities/index'
import { Route as AuthenticatedEducationScholarshipIndexRouteImport } from './routes/_authenticated/education/scholarship/index'
import { Route as AuthenticatedEducationRecipientsIndexRouteImport } from './routes/_authenticated/education/recipients/index'
import { Route as AuthenticatedEducationFairIndexRouteImport } from './routes/_authenticated/education/fair/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedHealthActivitiesFormRouteImport } from './routes/_authenticated/health/activities/form'
import { Route as AuthenticatedEducationScholarshipFormRouteImport } from './routes/_authenticated/education/scholarship/form'
import { Route as AuthenticatedEducationScholarshipCreateRouteImport } from './routes/_authenticated/education/scholarship/create'
import { Route as AuthenticatedEducationRecipientsCreateRouteImport } from './routes/_authenticated/education/recipients/create'
import { Route as AuthenticatedEducationFairFormRouteImport } from './routes/_authenticated/education/fair/form'
import { Route as AuthenticatedEducationFairCreateRouteImport } from './routes/_authenticated/education/fair/create'
import { Route as AuthenticatedAdminUsersFormRouteImport } from './routes/_authenticated/admin/users/form'
import { Route as AuthenticatedUserEducationScholarshipIndexRouteImport } from './routes/_authenticated/user/education/scholarship/index'
import { Route as AuthenticatedHealthActivitiesActivityIdIndexRouteImport } from './routes/_authenticated/health/activities/$activityId/index'
import { Route as AuthenticatedHealthActivitiesEditIdRouteImport } from './routes/_authenticated/health/activities/edit.$id'
import { Route as AuthenticatedHealthActivitiesActivityIdAssistanceRouteImport } from './routes/_authenticated/health/activities/$activityId/assistance'
import { Route as AuthenticatedEducationScholarshipScholarshipIdViewRouteImport } from './routes/_authenticated/education/scholarship/$scholarshipId/view'
import { Route as AuthenticatedUserEducationScholarshipIdViewRouteImport } from './routes/_authenticated/user/education/scholarship/$id/view'
import { Route as AuthenticatedHealthActivitiesActivityIdAttentionsUserIdRouteImport } from './routes/_authenticated/health/activities/$activityId/attentions/$userId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const LandingApplyRoute = LandingApplyRouteImport.update({
  id: '/landing/apply',
  path: '/landing/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedUserRoute = AuthenticatedUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizationRoute =
  AuthenticatedOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEducationRoute = AuthenticatedEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBeneficiaryRoute =
  AuthenticatedBeneficiaryRouteImport.update({
    id: '/beneficiary',
    path: '/beneficiary',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthWelcomeIndexRoute = AuthWelcomeIndexRouteImport.update({
  id: '/welcome_/',
  path: '/welcome/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedUserIndexRoute = AuthenticatedUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUserRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedOrganizationIndexRoute =
  AuthenticatedOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizationRoute,
  } as any)
const AuthenticatedHealthIndexRoute =
  AuthenticatedHealthIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHealthRoute,
  } as any)
const AuthenticatedEducationIndexRoute =
  AuthenticatedEducationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEducationRoute,
  } as any)
const AuthenticatedBeneficiaryIndexRoute =
  AuthenticatedBeneficiaryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBeneficiaryRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedUserOrganizationsRoute =
  AuthenticatedUserOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedUserRoute,
  } as any)
const AuthenticatedUserEducationRoute =
  AuthenticatedUserEducationRouteImport.update({
    id: '/education',
    path: '/education',
    getParentRoute: () => AuthenticatedUserRoute,
  } as any)
const AuthenticatedSettingsInvitationsRoute =
  AuthenticatedSettingsInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAuthenticationRoute =
  AuthenticatedSettingsAuthenticationRouteImport.update({
    id: '/authentication',
    path: '/authentication',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedAdminOrganizationsRoute =
  AuthenticatedAdminOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedHealthSpecialityIndexRoute =
  AuthenticatedHealthSpecialityIndexRouteImport.update({
    id: '/speciality/',
    path: '/speciality/',
    getParentRoute: () => AuthenticatedHealthRoute,
  } as any)
const AuthenticatedHealthAlliesIndexRoute =
  AuthenticatedHealthAlliesIndexRouteImport.update({
    id: '/allies/',
    path: '/allies/',
    getParentRoute: () => AuthenticatedHealthRoute,
  } as any)
const AuthenticatedHealthActivitiesIndexRoute =
  AuthenticatedHealthActivitiesIndexRouteImport.update({
    id: '/activities/',
    path: '/activities/',
    getParentRoute: () => AuthenticatedHealthRoute,
  } as any)
const AuthenticatedEducationScholarshipIndexRoute =
  AuthenticatedEducationScholarshipIndexRouteImport.update({
    id: '/scholarship/',
    path: '/scholarship/',
    getParentRoute: () => AuthenticatedEducationRoute,
  } as any)
const AuthenticatedEducationRecipientsIndexRoute =
  AuthenticatedEducationRecipientsIndexRouteImport.update({
    id: '/recipients/',
    path: '/recipients/',
    getParentRoute: () => AuthenticatedEducationRoute,
  } as any)
const AuthenticatedEducationFairIndexRoute =
  AuthenticatedEducationFairIndexRouteImport.update({
    id: '/fair/',
    path: '/fair/',
    getParentRoute: () => AuthenticatedEducationRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedHealthActivitiesFormRoute =
  AuthenticatedHealthActivitiesFormRouteImport.update({
    id: '/activities/form',
    path: '/activities/form',
    getParentRoute: () => AuthenticatedHealthRoute,
  } as any)
const AuthenticatedEducationScholarshipFormRoute =
  AuthenticatedEducationScholarshipFormRouteImport.update({
    id: '/scholarship/form',
    path: '/scholarship/form',
    getParentRoute: () => AuthenticatedEducationRoute,
  } as any)
const AuthenticatedEducationScholarshipCreateRoute =
  AuthenticatedEducationScholarshipCreateRouteImport.update({
    id: '/scholarship/create',
    path: '/scholarship/create',
    getParentRoute: () => AuthenticatedEducationRoute,
  } as any)
const AuthenticatedEducationRecipientsCreateRoute =
  AuthenticatedEducationRecipientsCreateRouteImport.update({
    id: '/recipients/create',
    path: '/recipients/create',
    getParentRoute: () => AuthenticatedEducationRoute,
  } as any)
const AuthenticatedEducationFairFormRoute =
  AuthenticatedEducationFairFormRouteImport.update({
    id: '/fair/form',
    path: '/fair/form',
    getParentRoute: () => AuthenticatedEducationRoute,
  } as any)
const AuthenticatedEducationFairCreateRoute =
  AuthenticatedEducationFairCreateRouteImport.update({
    id: '/fair/create',
    path: '/fair/create',
    getParentRoute: () => AuthenticatedEducationRoute,
  } as any)
const AuthenticatedAdminUsersFormRoute =
  AuthenticatedAdminUsersFormRouteImport.update({
    id: '/users/form',
    path: '/users/form',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedUserEducationScholarshipIndexRoute =
  AuthenticatedUserEducationScholarshipIndexRouteImport.update({
    id: '/scholarship/',
    path: '/scholarship/',
    getParentRoute: () => AuthenticatedUserEducationRoute,
  } as any)
const AuthenticatedHealthActivitiesActivityIdIndexRoute =
  AuthenticatedHealthActivitiesActivityIdIndexRouteImport.update({
    id: '/activities/$activityId/',
    path: '/activities/$activityId/',
    getParentRoute: () => AuthenticatedHealthRoute,
  } as any)
const AuthenticatedHealthActivitiesEditIdRoute =
  AuthenticatedHealthActivitiesEditIdRouteImport.update({
    id: '/activities/edit/$id',
    path: '/activities/edit/$id',
    getParentRoute: () => AuthenticatedHealthRoute,
  } as any)
const AuthenticatedHealthActivitiesActivityIdAssistanceRoute =
  AuthenticatedHealthActivitiesActivityIdAssistanceRouteImport.update({
    id: '/activities/$activityId/assistance',
    path: '/activities/$activityId/assistance',
    getParentRoute: () => AuthenticatedHealthRoute,
  } as any)
const AuthenticatedEducationScholarshipScholarshipIdViewRoute =
  AuthenticatedEducationScholarshipScholarshipIdViewRouteImport.update({
    id: '/scholarship/$scholarshipId/view',
    path: '/scholarship/$scholarshipId/view',
    getParentRoute: () => AuthenticatedEducationRoute,
  } as any)
const AuthenticatedUserEducationScholarshipIdViewRoute =
  AuthenticatedUserEducationScholarshipIdViewRouteImport.update({
    id: '/scholarship/$id/view',
    path: '/scholarship/$id/view',
    getParentRoute: () => AuthenticatedUserEducationRoute,
  } as any)
const AuthenticatedHealthActivitiesActivityIdAttentionsUserIdRoute =
  AuthenticatedHealthActivitiesActivityIdAttentionsUserIdRouteImport.update({
    id: '/activities/$activityId/attentions/$userId',
    path: '/activities/$activityId/attentions/$userId',
    getParentRoute: () => AuthenticatedHealthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/beneficiary': typeof AuthenticatedBeneficiaryRouteWithChildren
  '/education': typeof AuthenticatedEducationRouteWithChildren
  '/health': typeof AuthenticatedHealthRouteWithChildren
  '/organization': typeof AuthenticatedOrganizationRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/user': typeof AuthenticatedUserRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/landing/apply': typeof LandingApplyRoute
  '/auth/': typeof AuthIndexRoute
  '/landing': typeof LandingIndexRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/settings/authentication': typeof AuthenticatedSettingsAuthenticationRoute
  '/settings/invitations': typeof AuthenticatedSettingsInvitationsRoute
  '/user/education': typeof AuthenticatedUserEducationRouteWithChildren
  '/user/organizations': typeof AuthenticatedUserOrganizationsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/beneficiary/': typeof AuthenticatedBeneficiaryIndexRoute
  '/education/': typeof AuthenticatedEducationIndexRoute
  '/health/': typeof AuthenticatedHealthIndexRoute
  '/organization/': typeof AuthenticatedOrganizationIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/user/': typeof AuthenticatedUserIndexRoute
  '/auth/welcome': typeof AuthWelcomeIndexRoute
  '/admin/users/form': typeof AuthenticatedAdminUsersFormRoute
  '/education/fair/create': typeof AuthenticatedEducationFairCreateRoute
  '/education/fair/form': typeof AuthenticatedEducationFairFormRoute
  '/education/recipients/create': typeof AuthenticatedEducationRecipientsCreateRoute
  '/education/scholarship/create': typeof AuthenticatedEducationScholarshipCreateRoute
  '/education/scholarship/form': typeof AuthenticatedEducationScholarshipFormRoute
  '/health/activities/form': typeof AuthenticatedHealthActivitiesFormRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/education/fair': typeof AuthenticatedEducationFairIndexRoute
  '/education/recipients': typeof AuthenticatedEducationRecipientsIndexRoute
  '/education/scholarship': typeof AuthenticatedEducationScholarshipIndexRoute
  '/health/activities': typeof AuthenticatedHealthActivitiesIndexRoute
  '/health/allies': typeof AuthenticatedHealthAlliesIndexRoute
  '/health/speciality': typeof AuthenticatedHealthSpecialityIndexRoute
  '/education/scholarship/$scholarshipId/view': typeof AuthenticatedEducationScholarshipScholarshipIdViewRoute
  '/health/activities/$activityId/assistance': typeof AuthenticatedHealthActivitiesActivityIdAssistanceRoute
  '/health/activities/edit/$id': typeof AuthenticatedHealthActivitiesEditIdRoute
  '/health/activities/$activityId': typeof AuthenticatedHealthActivitiesActivityIdIndexRoute
  '/user/education/scholarship': typeof AuthenticatedUserEducationScholarshipIndexRoute
  '/health/activities/$activityId/attentions/$userId': typeof AuthenticatedHealthActivitiesActivityIdAttentionsUserIdRoute
  '/user/education/scholarship/$id/view': typeof AuthenticatedUserEducationScholarshipIdViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/landing/apply': typeof LandingApplyRoute
  '/auth': typeof AuthIndexRoute
  '/landing': typeof LandingIndexRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/settings/authentication': typeof AuthenticatedSettingsAuthenticationRoute
  '/settings/invitations': typeof AuthenticatedSettingsInvitationsRoute
  '/user/education': typeof AuthenticatedUserEducationRouteWithChildren
  '/user/organizations': typeof AuthenticatedUserOrganizationsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/beneficiary': typeof AuthenticatedBeneficiaryIndexRoute
  '/education': typeof AuthenticatedEducationIndexRoute
  '/health': typeof AuthenticatedHealthIndexRoute
  '/organization': typeof AuthenticatedOrganizationIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/user': typeof AuthenticatedUserIndexRoute
  '/auth/welcome': typeof AuthWelcomeIndexRoute
  '/admin/users/form': typeof AuthenticatedAdminUsersFormRoute
  '/education/fair/create': typeof AuthenticatedEducationFairCreateRoute
  '/education/fair/form': typeof AuthenticatedEducationFairFormRoute
  '/education/recipients/create': typeof AuthenticatedEducationRecipientsCreateRoute
  '/education/scholarship/create': typeof AuthenticatedEducationScholarshipCreateRoute
  '/education/scholarship/form': typeof AuthenticatedEducationScholarshipFormRoute
  '/health/activities/form': typeof AuthenticatedHealthActivitiesFormRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/education/fair': typeof AuthenticatedEducationFairIndexRoute
  '/education/recipients': typeof AuthenticatedEducationRecipientsIndexRoute
  '/education/scholarship': typeof AuthenticatedEducationScholarshipIndexRoute
  '/health/activities': typeof AuthenticatedHealthActivitiesIndexRoute
  '/health/allies': typeof AuthenticatedHealthAlliesIndexRoute
  '/health/speciality': typeof AuthenticatedHealthSpecialityIndexRoute
  '/education/scholarship/$scholarshipId/view': typeof AuthenticatedEducationScholarshipScholarshipIdViewRoute
  '/health/activities/$activityId/assistance': typeof AuthenticatedHealthActivitiesActivityIdAssistanceRoute
  '/health/activities/edit/$id': typeof AuthenticatedHealthActivitiesEditIdRoute
  '/health/activities/$activityId': typeof AuthenticatedHealthActivitiesActivityIdIndexRoute
  '/user/education/scholarship': typeof AuthenticatedUserEducationScholarshipIndexRoute
  '/health/activities/$activityId/attentions/$userId': typeof AuthenticatedHealthActivitiesActivityIdAttentionsUserIdRoute
  '/user/education/scholarship/$id/view': typeof AuthenticatedUserEducationScholarshipIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/beneficiary': typeof AuthenticatedBeneficiaryRouteWithChildren
  '/_authenticated/education': typeof AuthenticatedEducationRouteWithChildren
  '/_authenticated/health': typeof AuthenticatedHealthRouteWithChildren
  '/_authenticated/organization': typeof AuthenticatedOrganizationRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/user': typeof AuthenticatedUserRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/landing/apply': typeof LandingApplyRoute
  '/auth/': typeof AuthIndexRoute
  '/landing/': typeof LandingIndexRoute
  '/_authenticated/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/_authenticated/settings/authentication': typeof AuthenticatedSettingsAuthenticationRoute
  '/_authenticated/settings/invitations': typeof AuthenticatedSettingsInvitationsRoute
  '/_authenticated/user/education': typeof AuthenticatedUserEducationRouteWithChildren
  '/_authenticated/user/organizations': typeof AuthenticatedUserOrganizationsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/beneficiary/': typeof AuthenticatedBeneficiaryIndexRoute
  '/_authenticated/education/': typeof AuthenticatedEducationIndexRoute
  '/_authenticated/health/': typeof AuthenticatedHealthIndexRoute
  '/_authenticated/organization/': typeof AuthenticatedOrganizationIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/user/': typeof AuthenticatedUserIndexRoute
  '/auth/welcome_/': typeof AuthWelcomeIndexRoute
  '/_authenticated/admin/users/form': typeof AuthenticatedAdminUsersFormRoute
  '/_authenticated/education/fair/create': typeof AuthenticatedEducationFairCreateRoute
  '/_authenticated/education/fair/form': typeof AuthenticatedEducationFairFormRoute
  '/_authenticated/education/recipients/create': typeof AuthenticatedEducationRecipientsCreateRoute
  '/_authenticated/education/scholarship/create': typeof AuthenticatedEducationScholarshipCreateRoute
  '/_authenticated/education/scholarship/form': typeof AuthenticatedEducationScholarshipFormRoute
  '/_authenticated/health/activities/form': typeof AuthenticatedHealthActivitiesFormRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/education/fair/': typeof AuthenticatedEducationFairIndexRoute
  '/_authenticated/education/recipients/': typeof AuthenticatedEducationRecipientsIndexRoute
  '/_authenticated/education/scholarship/': typeof AuthenticatedEducationScholarshipIndexRoute
  '/_authenticated/health/activities/': typeof AuthenticatedHealthActivitiesIndexRoute
  '/_authenticated/health/allies/': typeof AuthenticatedHealthAlliesIndexRoute
  '/_authenticated/health/speciality/': typeof AuthenticatedHealthSpecialityIndexRoute
  '/_authenticated/education/scholarship/$scholarshipId/view': typeof AuthenticatedEducationScholarshipScholarshipIdViewRoute
  '/_authenticated/health/activities/$activityId/assistance': typeof AuthenticatedHealthActivitiesActivityIdAssistanceRoute
  '/_authenticated/health/activities/edit/$id': typeof AuthenticatedHealthActivitiesEditIdRoute
  '/_authenticated/health/activities/$activityId/': typeof AuthenticatedHealthActivitiesActivityIdIndexRoute
  '/_authenticated/user/education/scholarship/': typeof AuthenticatedUserEducationScholarshipIndexRoute
  '/_authenticated/health/activities/$activityId/attentions/$userId': typeof AuthenticatedHealthActivitiesActivityIdAttentionsUserIdRoute
  '/_authenticated/user/education/scholarship/$id/view': typeof AuthenticatedUserEducationScholarshipIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/beneficiary'
    | '/education'
    | '/health'
    | '/organization'
    | '/settings'
    | '/user'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/landing/apply'
    | '/auth/'
    | '/landing'
    | '/admin/organizations'
    | '/settings/authentication'
    | '/settings/invitations'
    | '/user/education'
    | '/user/organizations'
    | '/admin/'
    | '/beneficiary/'
    | '/education/'
    | '/health/'
    | '/organization/'
    | '/settings/'
    | '/user/'
    | '/auth/welcome'
    | '/admin/users/form'
    | '/education/fair/create'
    | '/education/fair/form'
    | '/education/recipients/create'
    | '/education/scholarship/create'
    | '/education/scholarship/form'
    | '/health/activities/form'
    | '/admin/users'
    | '/education/fair'
    | '/education/recipients'
    | '/education/scholarship'
    | '/health/activities'
    | '/health/allies'
    | '/health/speciality'
    | '/education/scholarship/$scholarshipId/view'
    | '/health/activities/$activityId/assistance'
    | '/health/activities/edit/$id'
    | '/health/activities/$activityId'
    | '/user/education/scholarship'
    | '/health/activities/$activityId/attentions/$userId'
    | '/user/education/scholarship/$id/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/landing/apply'
    | '/auth'
    | '/landing'
    | '/admin/organizations'
    | '/settings/authentication'
    | '/settings/invitations'
    | '/user/education'
    | '/user/organizations'
    | '/admin'
    | '/beneficiary'
    | '/education'
    | '/health'
    | '/organization'
    | '/settings'
    | '/user'
    | '/auth/welcome'
    | '/admin/users/form'
    | '/education/fair/create'
    | '/education/fair/form'
    | '/education/recipients/create'
    | '/education/scholarship/create'
    | '/education/scholarship/form'
    | '/health/activities/form'
    | '/admin/users'
    | '/education/fair'
    | '/education/recipients'
    | '/education/scholarship'
    | '/health/activities'
    | '/health/allies'
    | '/health/speciality'
    | '/education/scholarship/$scholarshipId/view'
    | '/health/activities/$activityId/assistance'
    | '/health/activities/edit/$id'
    | '/health/activities/$activityId'
    | '/user/education/scholarship'
    | '/health/activities/$activityId/attentions/$userId'
    | '/user/education/scholarship/$id/view'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/beneficiary'
    | '/_authenticated/education'
    | '/_authenticated/health'
    | '/_authenticated/organization'
    | '/_authenticated/settings'
    | '/_authenticated/user'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/landing/apply'
    | '/auth/'
    | '/landing/'
    | '/_authenticated/admin/organizations'
    | '/_authenticated/settings/authentication'
    | '/_authenticated/settings/invitations'
    | '/_authenticated/user/education'
    | '/_authenticated/user/organizations'
    | '/_authenticated/admin/'
    | '/_authenticated/beneficiary/'
    | '/_authenticated/education/'
    | '/_authenticated/health/'
    | '/_authenticated/organization/'
    | '/_authenticated/settings/'
    | '/_authenticated/user/'
    | '/auth/welcome_/'
    | '/_authenticated/admin/users/form'
    | '/_authenticated/education/fair/create'
    | '/_authenticated/education/fair/form'
    | '/_authenticated/education/recipients/create'
    | '/_authenticated/education/scholarship/create'
    | '/_authenticated/education/scholarship/form'
    | '/_authenticated/health/activities/form'
    | '/_authenticated/admin/users/'
    | '/_authenticated/education/fair/'
    | '/_authenticated/education/recipients/'
    | '/_authenticated/education/scholarship/'
    | '/_authenticated/health/activities/'
    | '/_authenticated/health/allies/'
    | '/_authenticated/health/speciality/'
    | '/_authenticated/education/scholarship/$scholarshipId/view'
    | '/_authenticated/health/activities/$activityId/assistance'
    | '/_authenticated/health/activities/edit/$id'
    | '/_authenticated/health/activities/$activityId/'
    | '/_authenticated/user/education/scholarship/'
    | '/_authenticated/health/activities/$activityId/attentions/$userId'
    | '/_authenticated/user/education/scholarship/$id/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  LandingApplyRoute: typeof LandingApplyRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/': {
      id: '/landing/'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/landing/apply': {
      id: '/landing/apply'
      path: '/landing/apply'
      fullPath: '/landing/apply'
      preLoaderRoute: typeof LandingApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/user': {
      id: '/_authenticated/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthenticatedUserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organization': {
      id: '/_authenticated/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AuthenticatedOrganizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/education': {
      id: '/_authenticated/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof AuthenticatedEducationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/beneficiary': {
      id: '/_authenticated/beneficiary'
      path: '/beneficiary'
      fullPath: '/beneficiary'
      preLoaderRoute: typeof AuthenticatedBeneficiaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/welcome_/': {
      id: '/auth/welcome_/'
      path: '/welcome'
      fullPath: '/auth/welcome'
      preLoaderRoute: typeof AuthWelcomeIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/user/': {
      id: '/_authenticated/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof AuthenticatedUserIndexRouteImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/organization/': {
      id: '/_authenticated/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof AuthenticatedOrganizationIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationRoute
    }
    '/_authenticated/health/': {
      id: '/_authenticated/health/'
      path: '/'
      fullPath: '/health/'
      preLoaderRoute: typeof AuthenticatedHealthIndexRouteImport
      parentRoute: typeof AuthenticatedHealthRoute
    }
    '/_authenticated/education/': {
      id: '/_authenticated/education/'
      path: '/'
      fullPath: '/education/'
      preLoaderRoute: typeof AuthenticatedEducationIndexRouteImport
      parentRoute: typeof AuthenticatedEducationRoute
    }
    '/_authenticated/beneficiary/': {
      id: '/_authenticated/beneficiary/'
      path: '/'
      fullPath: '/beneficiary/'
      preLoaderRoute: typeof AuthenticatedBeneficiaryIndexRouteImport
      parentRoute: typeof AuthenticatedBeneficiaryRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/user/organizations': {
      id: '/_authenticated/user/organizations'
      path: '/organizations'
      fullPath: '/user/organizations'
      preLoaderRoute: typeof AuthenticatedUserOrganizationsRouteImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    '/_authenticated/user/education': {
      id: '/_authenticated/user/education'
      path: '/education'
      fullPath: '/user/education'
      preLoaderRoute: typeof AuthenticatedUserEducationRouteImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    '/_authenticated/settings/invitations': {
      id: '/_authenticated/settings/invitations'
      path: '/invitations'
      fullPath: '/settings/invitations'
      preLoaderRoute: typeof AuthenticatedSettingsInvitationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/authentication': {
      id: '/_authenticated/settings/authentication'
      path: '/authentication'
      fullPath: '/settings/authentication'
      preLoaderRoute: typeof AuthenticatedSettingsAuthenticationRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/admin/organizations': {
      id: '/_authenticated/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/health/speciality/': {
      id: '/_authenticated/health/speciality/'
      path: '/speciality'
      fullPath: '/health/speciality'
      preLoaderRoute: typeof AuthenticatedHealthSpecialityIndexRouteImport
      parentRoute: typeof AuthenticatedHealthRoute
    }
    '/_authenticated/health/allies/': {
      id: '/_authenticated/health/allies/'
      path: '/allies'
      fullPath: '/health/allies'
      preLoaderRoute: typeof AuthenticatedHealthAlliesIndexRouteImport
      parentRoute: typeof AuthenticatedHealthRoute
    }
    '/_authenticated/health/activities/': {
      id: '/_authenticated/health/activities/'
      path: '/activities'
      fullPath: '/health/activities'
      preLoaderRoute: typeof AuthenticatedHealthActivitiesIndexRouteImport
      parentRoute: typeof AuthenticatedHealthRoute
    }
    '/_authenticated/education/scholarship/': {
      id: '/_authenticated/education/scholarship/'
      path: '/scholarship'
      fullPath: '/education/scholarship'
      preLoaderRoute: typeof AuthenticatedEducationScholarshipIndexRouteImport
      parentRoute: typeof AuthenticatedEducationRoute
    }
    '/_authenticated/education/recipients/': {
      id: '/_authenticated/education/recipients/'
      path: '/recipients'
      fullPath: '/education/recipients'
      preLoaderRoute: typeof AuthenticatedEducationRecipientsIndexRouteImport
      parentRoute: typeof AuthenticatedEducationRoute
    }
    '/_authenticated/education/fair/': {
      id: '/_authenticated/education/fair/'
      path: '/fair'
      fullPath: '/education/fair'
      preLoaderRoute: typeof AuthenticatedEducationFairIndexRouteImport
      parentRoute: typeof AuthenticatedEducationRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/health/activities/form': {
      id: '/_authenticated/health/activities/form'
      path: '/activities/form'
      fullPath: '/health/activities/form'
      preLoaderRoute: typeof AuthenticatedHealthActivitiesFormRouteImport
      parentRoute: typeof AuthenticatedHealthRoute
    }
    '/_authenticated/education/scholarship/form': {
      id: '/_authenticated/education/scholarship/form'
      path: '/scholarship/form'
      fullPath: '/education/scholarship/form'
      preLoaderRoute: typeof AuthenticatedEducationScholarshipFormRouteImport
      parentRoute: typeof AuthenticatedEducationRoute
    }
    '/_authenticated/education/scholarship/create': {
      id: '/_authenticated/education/scholarship/create'
      path: '/scholarship/create'
      fullPath: '/education/scholarship/create'
      preLoaderRoute: typeof AuthenticatedEducationScholarshipCreateRouteImport
      parentRoute: typeof AuthenticatedEducationRoute
    }
    '/_authenticated/education/recipients/create': {
      id: '/_authenticated/education/recipients/create'
      path: '/recipients/create'
      fullPath: '/education/recipients/create'
      preLoaderRoute: typeof AuthenticatedEducationRecipientsCreateRouteImport
      parentRoute: typeof AuthenticatedEducationRoute
    }
    '/_authenticated/education/fair/form': {
      id: '/_authenticated/education/fair/form'
      path: '/fair/form'
      fullPath: '/education/fair/form'
      preLoaderRoute: typeof AuthenticatedEducationFairFormRouteImport
      parentRoute: typeof AuthenticatedEducationRoute
    }
    '/_authenticated/education/fair/create': {
      id: '/_authenticated/education/fair/create'
      path: '/fair/create'
      fullPath: '/education/fair/create'
      preLoaderRoute: typeof AuthenticatedEducationFairCreateRouteImport
      parentRoute: typeof AuthenticatedEducationRoute
    }
    '/_authenticated/admin/users/form': {
      id: '/_authenticated/admin/users/form'
      path: '/users/form'
      fullPath: '/admin/users/form'
      preLoaderRoute: typeof AuthenticatedAdminUsersFormRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/user/education/scholarship/': {
      id: '/_authenticated/user/education/scholarship/'
      path: '/scholarship'
      fullPath: '/user/education/scholarship'
      preLoaderRoute: typeof AuthenticatedUserEducationScholarshipIndexRouteImport
      parentRoute: typeof AuthenticatedUserEducationRoute
    }
    '/_authenticated/health/activities/$activityId/': {
      id: '/_authenticated/health/activities/$activityId/'
      path: '/activities/$activityId'
      fullPath: '/health/activities/$activityId'
      preLoaderRoute: typeof AuthenticatedHealthActivitiesActivityIdIndexRouteImport
      parentRoute: typeof AuthenticatedHealthRoute
    }
    '/_authenticated/health/activities/edit/$id': {
      id: '/_authenticated/health/activities/edit/$id'
      path: '/activities/edit/$id'
      fullPath: '/health/activities/edit/$id'
      preLoaderRoute: typeof AuthenticatedHealthActivitiesEditIdRouteImport
      parentRoute: typeof AuthenticatedHealthRoute
    }
    '/_authenticated/health/activities/$activityId/assistance': {
      id: '/_authenticated/health/activities/$activityId/assistance'
      path: '/activities/$activityId/assistance'
      fullPath: '/health/activities/$activityId/assistance'
      preLoaderRoute: typeof AuthenticatedHealthActivitiesActivityIdAssistanceRouteImport
      parentRoute: typeof AuthenticatedHealthRoute
    }
    '/_authenticated/education/scholarship/$scholarshipId/view': {
      id: '/_authenticated/education/scholarship/$scholarshipId/view'
      path: '/scholarship/$scholarshipId/view'
      fullPath: '/education/scholarship/$scholarshipId/view'
      preLoaderRoute: typeof AuthenticatedEducationScholarshipScholarshipIdViewRouteImport
      parentRoute: typeof AuthenticatedEducationRoute
    }
    '/_authenticated/user/education/scholarship/$id/view': {
      id: '/_authenticated/user/education/scholarship/$id/view'
      path: '/scholarship/$id/view'
      fullPath: '/user/education/scholarship/$id/view'
      preLoaderRoute: typeof AuthenticatedUserEducationScholarshipIdViewRouteImport
      parentRoute: typeof AuthenticatedUserEducationRoute
    }
    '/_authenticated/health/activities/$activityId/attentions/$userId': {
      id: '/_authenticated/health/activities/$activityId/attentions/$userId'
      path: '/activities/$activityId/attentions/$userId'
      fullPath: '/health/activities/$activityId/attentions/$userId'
      preLoaderRoute: typeof AuthenticatedHealthActivitiesActivityIdAttentionsUserIdRouteImport
      parentRoute: typeof AuthenticatedHealthRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminOrganizationsRoute: typeof AuthenticatedAdminOrganizationsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminUsersFormRoute: typeof AuthenticatedAdminUsersFormRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminOrganizationsRoute: AuthenticatedAdminOrganizationsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminUsersFormRoute: AuthenticatedAdminUsersFormRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedBeneficiaryRouteChildren {
  AuthenticatedBeneficiaryIndexRoute: typeof AuthenticatedBeneficiaryIndexRoute
}

const AuthenticatedBeneficiaryRouteChildren: AuthenticatedBeneficiaryRouteChildren =
  {
    AuthenticatedBeneficiaryIndexRoute: AuthenticatedBeneficiaryIndexRoute,
  }

const AuthenticatedBeneficiaryRouteWithChildren =
  AuthenticatedBeneficiaryRoute._addFileChildren(
    AuthenticatedBeneficiaryRouteChildren,
  )

interface AuthenticatedEducationRouteChildren {
  AuthenticatedEducationIndexRoute: typeof AuthenticatedEducationIndexRoute
  AuthenticatedEducationFairCreateRoute: typeof AuthenticatedEducationFairCreateRoute
  AuthenticatedEducationFairFormRoute: typeof AuthenticatedEducationFairFormRoute
  AuthenticatedEducationRecipientsCreateRoute: typeof AuthenticatedEducationRecipientsCreateRoute
  AuthenticatedEducationScholarshipCreateRoute: typeof AuthenticatedEducationScholarshipCreateRoute
  AuthenticatedEducationScholarshipFormRoute: typeof AuthenticatedEducationScholarshipFormRoute
  AuthenticatedEducationFairIndexRoute: typeof AuthenticatedEducationFairIndexRoute
  AuthenticatedEducationRecipientsIndexRoute: typeof AuthenticatedEducationRecipientsIndexRoute
  AuthenticatedEducationScholarshipIndexRoute: typeof AuthenticatedEducationScholarshipIndexRoute
  AuthenticatedEducationScholarshipScholarshipIdViewRoute: typeof AuthenticatedEducationScholarshipScholarshipIdViewRoute
}

const AuthenticatedEducationRouteChildren: AuthenticatedEducationRouteChildren =
  {
    AuthenticatedEducationIndexRoute: AuthenticatedEducationIndexRoute,
    AuthenticatedEducationFairCreateRoute:
      AuthenticatedEducationFairCreateRoute,
    AuthenticatedEducationFairFormRoute: AuthenticatedEducationFairFormRoute,
    AuthenticatedEducationRecipientsCreateRoute:
      AuthenticatedEducationRecipientsCreateRoute,
    AuthenticatedEducationScholarshipCreateRoute:
      AuthenticatedEducationScholarshipCreateRoute,
    AuthenticatedEducationScholarshipFormRoute:
      AuthenticatedEducationScholarshipFormRoute,
    AuthenticatedEducationFairIndexRoute: AuthenticatedEducationFairIndexRoute,
    AuthenticatedEducationRecipientsIndexRoute:
      AuthenticatedEducationRecipientsIndexRoute,
    AuthenticatedEducationScholarshipIndexRoute:
      AuthenticatedEducationScholarshipIndexRoute,
    AuthenticatedEducationScholarshipScholarshipIdViewRoute:
      AuthenticatedEducationScholarshipScholarshipIdViewRoute,
  }

const AuthenticatedEducationRouteWithChildren =
  AuthenticatedEducationRoute._addFileChildren(
    AuthenticatedEducationRouteChildren,
  )

interface AuthenticatedHealthRouteChildren {
  AuthenticatedHealthIndexRoute: typeof AuthenticatedHealthIndexRoute
  AuthenticatedHealthActivitiesFormRoute: typeof AuthenticatedHealthActivitiesFormRoute
  AuthenticatedHealthActivitiesIndexRoute: typeof AuthenticatedHealthActivitiesIndexRoute
  AuthenticatedHealthAlliesIndexRoute: typeof AuthenticatedHealthAlliesIndexRoute
  AuthenticatedHealthSpecialityIndexRoute: typeof AuthenticatedHealthSpecialityIndexRoute
  AuthenticatedHealthActivitiesActivityIdAssistanceRoute: typeof AuthenticatedHealthActivitiesActivityIdAssistanceRoute
  AuthenticatedHealthActivitiesEditIdRoute: typeof AuthenticatedHealthActivitiesEditIdRoute
  AuthenticatedHealthActivitiesActivityIdIndexRoute: typeof AuthenticatedHealthActivitiesActivityIdIndexRoute
  AuthenticatedHealthActivitiesActivityIdAttentionsUserIdRoute: typeof AuthenticatedHealthActivitiesActivityIdAttentionsUserIdRoute
}

const AuthenticatedHealthRouteChildren: AuthenticatedHealthRouteChildren = {
  AuthenticatedHealthIndexRoute: AuthenticatedHealthIndexRoute,
  AuthenticatedHealthActivitiesFormRoute:
    AuthenticatedHealthActivitiesFormRoute,
  AuthenticatedHealthActivitiesIndexRoute:
    AuthenticatedHealthActivitiesIndexRoute,
  AuthenticatedHealthAlliesIndexRoute: AuthenticatedHealthAlliesIndexRoute,
  AuthenticatedHealthSpecialityIndexRoute:
    AuthenticatedHealthSpecialityIndexRoute,
  AuthenticatedHealthActivitiesActivityIdAssistanceRoute:
    AuthenticatedHealthActivitiesActivityIdAssistanceRoute,
  AuthenticatedHealthActivitiesEditIdRoute:
    AuthenticatedHealthActivitiesEditIdRoute,
  AuthenticatedHealthActivitiesActivityIdIndexRoute:
    AuthenticatedHealthActivitiesActivityIdIndexRoute,
  AuthenticatedHealthActivitiesActivityIdAttentionsUserIdRoute:
    AuthenticatedHealthActivitiesActivityIdAttentionsUserIdRoute,
}

const AuthenticatedHealthRouteWithChildren =
  AuthenticatedHealthRoute._addFileChildren(AuthenticatedHealthRouteChildren)

interface AuthenticatedOrganizationRouteChildren {
  AuthenticatedOrganizationIndexRoute: typeof AuthenticatedOrganizationIndexRoute
}

const AuthenticatedOrganizationRouteChildren: AuthenticatedOrganizationRouteChildren =
  {
    AuthenticatedOrganizationIndexRoute: AuthenticatedOrganizationIndexRoute,
  }

const AuthenticatedOrganizationRouteWithChildren =
  AuthenticatedOrganizationRoute._addFileChildren(
    AuthenticatedOrganizationRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAuthenticationRoute: typeof AuthenticatedSettingsAuthenticationRoute
  AuthenticatedSettingsInvitationsRoute: typeof AuthenticatedSettingsInvitationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAuthenticationRoute:
    AuthenticatedSettingsAuthenticationRoute,
  AuthenticatedSettingsInvitationsRoute: AuthenticatedSettingsInvitationsRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedUserEducationRouteChildren {
  AuthenticatedUserEducationScholarshipIndexRoute: typeof AuthenticatedUserEducationScholarshipIndexRoute
  AuthenticatedUserEducationScholarshipIdViewRoute: typeof AuthenticatedUserEducationScholarshipIdViewRoute
}

const AuthenticatedUserEducationRouteChildren: AuthenticatedUserEducationRouteChildren =
  {
    AuthenticatedUserEducationScholarshipIndexRoute:
      AuthenticatedUserEducationScholarshipIndexRoute,
    AuthenticatedUserEducationScholarshipIdViewRoute:
      AuthenticatedUserEducationScholarshipIdViewRoute,
  }

const AuthenticatedUserEducationRouteWithChildren =
  AuthenticatedUserEducationRoute._addFileChildren(
    AuthenticatedUserEducationRouteChildren,
  )

interface AuthenticatedUserRouteChildren {
  AuthenticatedUserEducationRoute: typeof AuthenticatedUserEducationRouteWithChildren
  AuthenticatedUserOrganizationsRoute: typeof AuthenticatedUserOrganizationsRoute
  AuthenticatedUserIndexRoute: typeof AuthenticatedUserIndexRoute
}

const AuthenticatedUserRouteChildren: AuthenticatedUserRouteChildren = {
  AuthenticatedUserEducationRoute: AuthenticatedUserEducationRouteWithChildren,
  AuthenticatedUserOrganizationsRoute: AuthenticatedUserOrganizationsRoute,
  AuthenticatedUserIndexRoute: AuthenticatedUserIndexRoute,
}

const AuthenticatedUserRouteWithChildren =
  AuthenticatedUserRoute._addFileChildren(AuthenticatedUserRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBeneficiaryRoute: typeof AuthenticatedBeneficiaryRouteWithChildren
  AuthenticatedEducationRoute: typeof AuthenticatedEducationRouteWithChildren
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRouteWithChildren
  AuthenticatedOrganizationRoute: typeof AuthenticatedOrganizationRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedUserRoute: typeof AuthenticatedUserRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBeneficiaryRoute: AuthenticatedBeneficiaryRouteWithChildren,
  AuthenticatedEducationRoute: AuthenticatedEducationRouteWithChildren,
  AuthenticatedHealthRoute: AuthenticatedHealthRouteWithChildren,
  AuthenticatedOrganizationRoute: AuthenticatedOrganizationRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedUserRoute: AuthenticatedUserRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthWelcomeIndexRoute: typeof AuthWelcomeIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthWelcomeIndexRoute: AuthWelcomeIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  LandingApplyRoute: LandingApplyRoute,
  LandingIndexRoute: LandingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
